version: '3'
services:
  app:
    container_name: flask-selenium
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/opt/app
    ports:
      - 9090:8080
    environment:
      - PORT=8080
    command: gunicorn --bind :8080 --workers 1 --threads 8 --timeout 0 --reload main:app